### ISSUE TITLE
[Bug] Cannot switch configurations without changing default

### ISSUE THREAD

**Issue by cashmonger** [aquariumbio/pfish#43]
If you have "local" set as your default configuration, but you want to use your "production" configuration, you have to set "production" as the default. You should be able to change this on the fly using the "-n" flag without changing the default. 

`pfish pull -n production`

**Comment by dvnstrcklnd** [comment]
I'd like to upvote this one. Having to change the default in order to push to a production server is really dangerous.

**Comment by bjkeller** [comment]
@cashmonger the name argument is there for all of the relevant commands, but needs to be passed into create_session when set.

I suggest removing the default on --name so that it is easier to check if it is set
